os: osx
language: generic
sudo: required
dist: trusty
osx_image: xcode11
before_install:
  - brew update
  - brew install swiftlint || true
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test
notifications:
  email: false
